# Generated by Django 4.0.1 on 2022-02-03 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hassanApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('grades', models.BooleanField(verbose_name='')),
            ],
        ),
    ]
