# Generated by Django 4.0.1 on 2022-02-03 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hassanApp', '0002_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
